export enum responseEnum {
  GET_USER = 'User fetched successfully.',
  GET_ALL_USERS = 'User(s) fetched successfully.',
  EMPLOYEE_NOT_FOUND = 'Employee(s) not found.',
  USERS_ALREADY_EXISTS = 'User already exists.',
  USER_CREATED = 'User create successfully.',
  USER_UPDATED = 'User updated successfully.',
  USER_UPDATE_FAILED = 'Failed to Update the User',
  NOT_DATA = 'There is nothing to save',
  PERMISSIONS_NOT_FOUND = 'Permissions not found.',
  CLIENT_NOT_FOUND = 'Client(s) not found.',
  DEALER_NOT_FOUND = 'Dealer(s) not found.',
  PROFILE_FOUND = 'PROFILE fetched successfully.',
  PROFILE_NOT_FOUND = 'Unable to fetch PROFILE.',
}
