title: "perf: "
name: "\U0001F525 Suggestion for Improving Performance"
description: "I have a suggestion that might improve the performance of Nest \U00002728"
labels: ["type: enhancement :wolf:", "needs triage"]
body:
  - type: checkboxes
    attributes:
      label: "Is there an existing issue that is already proposing this?"
      description: "Please search [here](../issues?q=is%3Aissue) to see if an issue already exists for this"
      options:
      - label: "I have searched the existing issues"
        required: true
          
  - type: dropdown
    validations:
      required: true
    attributes:
      label: "Project Name"
      description: "Select the project you intend to improve"
      options:
        - "Main"
        - "01-Mongoose"

  - type: input
    validations:
      required: true
    attributes:
      label: "NestJS version"
      description: "Which version do you intend to improve?"
      placeholder: "8.1.3"

  - type: textarea
    attributes:
      label: "Is your performance suggestion related to a problem? Please describe it"
      description: "A clear and concise description of what the problem is"

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Describe the performance enhancement you are proposing and how we can try it out"
      placeholder: |
        Cache `array.length` on the following lines ...